import Head from 'next/head'
import Content from '../layout/Content'
import Depositions from '../layout/Depositions'
import Footer from '../layout/Footer'
import Home from '../layout/Home'
import Objections from '../layout/Objections'
import Ofert from '../layout/Ofert'
import Professor from '../layout/Professor'
import Questions from '../layout/Questions'
import Warranty from '../layout/Warranty'

export default function Index() {
  return (
    <>
      <Head>
        <title>Virando Herói - Se torne um herói de uma vez por todas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home/>
      <Objections/>
      <Content/>
      <Depositions/>
      <Professor/>
      <Ofert/>
      <Warranty/>
      <Questions/>
      <Footer/>
    </>
  )
}
